# Text Representation 

In [1]:
# 1. Bag of words 
# we use countvectorization 

In [2]:
import numpy as np 
import pandas as pd 

In [3]:
df = pd.DataFrame({'text':['people watch cricket' , 'player was player' , 'people write comment' , 'cricket play comment' ] , 'output':[1,1,0,0]})

In [4]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer 

In [6]:
cv = CountVectorizer() 

In [7]:
bow = cv.fit_transform(df['text'])

In [8]:
# vocab 
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [9]:
print(bow[0].toarray()) 
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [10]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [11]:
# 2.N-grams

In [12]:
# cv = CountVectorizer(ngram_range(2,2))

In [13]:
v = CountVectorizer(ngram_range=(1, 2))
# v = CountVectorizer(ngram_range=(2, 2))

In [14]:
bow =  v.fit_transform(df['text'])

In [15]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [16]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [17]:
# TF(Term Frequencey) 
# 2. IDF(Inverse Document Frequencey)

In [18]:
# TF(t,d) = (Number of occurences of term t in document d)/(Total number of terms in the document d) 

# example ==>
# d1 = people watch cricket . 

# tf(people,d1) = 1/3 

# d2 = match was match. 
# tf(match , d2) = 2/3 

In [19]:
# IDF(t) = loge(Total number of documents in the corpus)/(Number of documents with term t in them) 
# here corpus means number of sentences

# Example ==>
# d1 = people watch cricket . 
# d2 = cricket was cricket . 
# d3 = people write comment .
# d4 = cricket write comment . 


# idf(cricket) = log(4/4)
# idf(people) = log(4/2) 

In [20]:
# we can use this by apply feature_extraction method in sklearn 

In [25]:
print(df)
print(df.info())

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    4 non-null      object
 1   output  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes
None


In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf = TfidfVectorizer() 
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [23]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


# WordEmbedding

# In natural language preprocessing , word embedding is a term used for the representation of words for text analysis , typically in the form of a real-valued vector that encodes the meaning of the word such that the words that are closer in the vector space are expected to be similar in meaning . 

In [24]:
# type of embeddings ==> 1. frequencey ==> Ex. bagofwords , tf , idf , glove(global veector) . 
# 2. prediction based embedding ==> word2vec 

# example ==> We will use the pre trained weights of word2vec that was trained on google new corpus containing 3 billion words. This model consists of 300-dimensional vectors for 3 million words and phrases. 